// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// col_min_idx
arma::uword col_min_idx(const arma::colvec u, const arma::ucolvec wlmt);
RcppExport SEXP skm_col_min_idx(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec >::type wlmt(wlmtSEXP);
    __result = Rcpp::wrap(col_min_idx(u, wlmt));
    return __result;
END_RCPP
}
// col_max_idx
arma::uword col_max_idx(const arma::colvec u, const arma::ucolvec wlmt);
RcppExport SEXP skm_col_max_idx(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec >::type wlmt(wlmtSEXP);
    __result = Rcpp::wrap(col_max_idx(u, wlmt));
    return __result;
END_RCPP
}
// col_min_val
double col_min_val(const arma::colvec u, const arma::ucolvec wlmt);
RcppExport SEXP skm_col_min_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec >::type wlmt(wlmtSEXP);
    __result = Rcpp::wrap(col_min_val(u, wlmt));
    return __result;
END_RCPP
}
// col_max_val
double col_max_val(const arma::colvec u, const arma::ucolvec wlmt);
RcppExport SEXP skm_col_max_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec >::type wlmt(wlmtSEXP);
    __result = Rcpp::wrap(col_max_val(u, wlmt));
    return __result;
END_RCPP
}
// col_rgn_val
double col_rgn_val(const arma::colvec u, const arma::ucolvec wlmt);
RcppExport SEXP skm_col_rgn_val(SEXP uSEXP, SEXP wlmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::ucolvec >::type wlmt(wlmtSEXP);
    __result = Rcpp::wrap(col_rgn_val(u, wlmt));
    return __result;
END_RCPP
}
// rgn_vec
arma::uvec rgn_vec(arma::uword s, arma::uword z);
RcppExport SEXP skm_rgn_vec(SEXP sSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::uword >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type z(zSEXP);
    __result = Rcpp::wrap(rgn_vec(s, z));
    return __result;
END_RCPP
}
// skm_minmax_cpp
arma::uvec skm_minmax_cpp(arma::mat x);
RcppExport SEXP skm_skm_minmax_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(skm_minmax_cpp(x));
    return __result;
END_RCPP
}
// skm_cpp
int skm_cpp(NumericMatrix x);
RcppExport SEXP skm_skm_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(skm_cpp(x));
    return __result;
END_RCPP
}
