# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' col_min_idx: colvec min value index within limited range
#' @param wlmt: a limit search on colvec on indices within wlmt
#' @return return an index of min value w.r.t to original index
#' @note cpp use index start from 0 vs r use index start from 1
#' @note in case of equal std:min/std:max take first index seen
col_min_idx <- function(u, wlmt) {
    .Call('skm_col_min_idx', PACKAGE = 'skm', u, wlmt)
}

#' col_max_idx: colvec max value index within limited range
#' @param wlmt: a limit search on colvec on indices within wlmt
#' @return return an index of max value w.r.t to original index
#' @note cpp use index start from 0 vs r use index start from 1
#' @note in case of equal std:min/std:max take first index seen
col_max_idx <- function(u, wlmt) {
    .Call('skm_col_max_idx', PACKAGE = 'skm', u, wlmt)
}

#' col_min_val: colvec min value within limited range
col_min_val <- function(u, wlmt) {
    .Call('skm_col_min_val', PACKAGE = 'skm', u, wlmt)
}

#' col_max_val: colvec max value within limited range
col_max_val <- function(u, wlmt) {
    .Call('skm_col_max_val', PACKAGE = 'skm', u, wlmt)
}

#' col_rgn_val: colvec diff max min value within limited range
col_rgn_val <- function(u, wlmt) {
    .Call('skm_col_rgn_val', PACKAGE = 'skm', u, wlmt)
}

#' rgn_vec: colvec range from s to z or from 0 to s when z NIL
rgn_vec <- function(s, z = 0L) {
    .Call('skm_rgn_vec', PACKAGE = 'skm', s, z)
}

#' skm_minmax_cpp: skm via min-max on in cpp.
#' skm_minmax_cpp with an input m x n matrix: objective is to select n of m st
#' minimize sum(min(<i, j> where i <1..n> and j <1..n> each use <1..n> once)).
#' so in case m <= n it simply select all m - should always be apply on matrix
#' with m > n - it is designed as a expectation step in skm_cpp on updating s.
#' it select i in <1..m> such that i has the colwise_min_idx on column j where
#' j has max difference of (colwise_max_val - colwise_min_val), it then remove
#' row i col j from matrix and repeat.
#' example skm_minmax_cpp is superior in bouding worst case compare to greedy:
#' x = [1 100; 4 200; 2 400; 9 900]: greedy 1 then 200, min-max 100 then 2, so
#' greedy give [1 100; 4 200] with 201 and minmax give [1 100; 2 400] with 102
NULL

skm_minmax_cpp <- function(x, s_must) {
    .Call('skm_skm_minmax_cpp', PACKAGE = 'skm', x, s_must)
}

skm_cpp <- function(x, s_init, s_must, max_it = 2L) {
    .Call('skm_skm_cpp', PACKAGE = 'skm', x, s_init, s_must, max_it)
}

